-- ─────────────────────────────────────────────────────────────────────────────
--  Dayton Relo — Events Table
--  Paste this entire file into Supabase → SQL Editor → Run
--  After this you manage all events from the Supabase Table Editor — no code needed.
-- ─────────────────────────────────────────────────────────────────────────────

create table if not exists public.events (
  id          text        primary key,
  title       text        not null,
  date        text        not null,
  month       text        not null,
  day         text        not null,
  venue       text        not null,
  category    text        not null check (category in ('music','festival','sports','arts','family','food')),
  is_free     boolean     not null default false,
  price       text,
  description text        not null,
  url         text        not null,
  is_active   boolean     not null default true,
  sort_order  integer     not null default 0,
  created_at  timestamptz not null default now()
);

-- Allow public read (no auth required to view events in the app)
alter table public.events enable row level security;
create policy "Events are publicly readable"
  on public.events for select
  using (true);

-- ─── Seed all events ─────────────────────────────────────────────────────────
insert into public.events
  (id, title, date, month, day, venue, category, is_free, price, description, url, sort_order)
values

-- April
('bob-dylan-2026',       'Bob Dylan',                                  'Apr 12, 2026',              'APR','12', 'Schuster Center, Downtown Dayton',        'music',   false, '$60–$150',              'A living legend on tour. Bob Dylan at the Schuster Center — one of those nights you''ll talk about forever.',                                                                              'https://www.daytonlive.org',                   10),
('wgi-2026',             'WGI World Championships',                    'Apr 15–18, 2026',           'APR','15', 'UD Arena & Nutter Center, Dayton',         'arts',    false, '$20–$80',               'The Super Bowl of indoor percussion and color guard. 30,000+ fans watch the world''s best performing ensembles compete — Dayton hosts this every year.',                                    'https://www.wgi.org',                          20),
('eastern-europe-fest',  'Eastern Europe Festival',                    'Apr 18, 2026',              'APR','18', 'Dayton Art Institute',                     'festival', true,  null,                   'Celebrate Eastern European food, folk dance, music, and cultural traditions from Polish, Ukrainian, Hungarian, and Czech communities. Free admission.',                                   'https://www.daytonartinstitute.org',            30),
('sugar-maple-2026',     'Bellbrook Sugar Maple Festival',             'Apr 24–26, 2026',           'APR','24', 'Downtown Bellbrook',                       'festival', true,  null,                   'One of the Miami Valley''s most beloved spring festivals — maple syrup demos, arts & crafts, food, live music, and carnival rides in charming downtown Bellbrook.',                      'https://bellbrooksugarmaplefestival.com',       40),
('alice-cooper-2026',    'Alice Cooper',                               'Apr 25, 2026',              'APR','25', 'Rose Music Center, Huber Heights',         'music',   false, '$45–$95',               'The godfather of shock rock brings his full theatrical live show to the Rose Music Center. An unforgettable night of classic rock spectacle.',                                              'https://rosemusiccenter.com',                  50),
('dragons-2026',         'Dayton Dragons Baseball',                    'Apr 7 – Sep 6, 2026',       'APR','7',  'Day Air Ballpark, Downtown Dayton',        'sports',  false, '$9–$16',                'Dayton''s beloved Single-A Reds affiliate. Perennial sellout crowds, Fireworks Fridays, theme nights, and the best family entertainment deal in town.',                                    'https://www.milb.com/dayton',                  60),

-- May
('levitt-2026',          'Levitt Pavilion Free Concert Series',        'May – Sep 2026 (Fri & Sat nights)', 'MAY','1',  'Levitt Pavilion, West Carrollton',  'music',    true,  null,                   '50+ free outdoor concerts every summer on the riverfront stage. National touring acts and local legends — no tickets, no cover, just show up.',                                            'https://levittdayton.org',                     70),
('third-day-2026',       'Third Day — 30th Anniversary Tour',          'May 7, 2026',               'MAY','7',  'Nutter Center, Fairborn',                 'music',   false, '$35–$75',               'Grammy-winning Christian rock band Third Day reunites for their 30th anniversary tour. An emotional and powerful night for longtime fans.',                                                  'https://www.nuttercenter.com',                 80),
('brit-floyd-2026',      'Brit Floyd — Wish You Were Here 50th Anniversary', 'May 15, 2026',        'MAY','15', 'Rose Music Center, Huber Heights',         'music',   false, '$40–$85',               'The world''s greatest Pink Floyd tribute celebrates the 50th anniversary of Wish You Were Here with a full production light show and note-perfect performance.',                            'https://rosemusiccenter.com',                  90),
('hamvention-2026',      'Dayton Hamvention',                          'May 15–17, 2026',           'MAY','15', 'Greene County Expo Center, Xenia',         'festival', false, '$30 (3-day pass)',      'The world''s largest amateur radio event — 30,000+ attendees, massive flea market, tech exhibits, and awards. A Dayton tradition since 1952.',                                             'https://hamvention.org',                      100),
('miamisburg-spring-fest','Miamisburg Spring Fest',                    'May 15–17, 2026',           'MAY','15', 'Riverfront Park, Miamisburg',              'festival', true,  null,                   'Three days of local art, live music, food trucks, and carnival rides on the banks of the Great Miami River — a feel-good community kickoff to summer.',                                   'https://www.miamisburg.org',                  110),
('oregon-district-arts', 'Oregon District Arts Festival',              'May 16–17, 2026',           'MAY','16', 'Oregon District, Dayton',                 'arts',     true,  null,                   '200+ artists fill Dayton''s most vibrant neighborhood with fine art, crafts, and live music — plus the best restaurant strip in the city right outside.',                                 'https://theoregondistrict.org',               120),
('george-thorogood-2026','George Thorogood & The Destroyers',          'May 22, 2026',              'MAY','22', 'Rose Music Center, Huber Heights',         'music',   false, '$35–$70',               'The legendary blues-rock outfit brings Who Do You Love and Bad to the Bone to the outdoor amphitheater. Pure American rock and roll.',                                                       'https://rosemusiccenter.com',                 130),
('jewish-cultural-fest', 'Temple Israel Jewish Cultural Festival',     'May 31, 2026',              'MAY','31', 'Temple Israel, Dayton',                   'festival', true,  null,                   'A welcoming community celebration of Jewish history and culture — food, music, dancing, games, and educational exhibits. Open and free to all.',                                           'https://www.tioh.org',                        140),

-- June
('warrant-fraze-2026',   'Warrant, Firehouse & BulletBoys',           'Jun 12, 2026',              'JUN','12', 'Fraze Pavilion, Kettering',               'music',   false, '$30–$60',               'Three iconic hair metal bands on one stage — Cherry Pie, I Live My Life for You, and Smooth Up In Ya. The ultimate 80s rock nostalgia night.',                                              'https://fraze.com',                           150),
('lynyrd-skynyrd-2026',  'Lynyrd Skynyrd',                             'Jun 15, 2026',              'JUN','15', 'Rose Music Center, Huber Heights',         'music',   false, '$45–$100',              'Sweet Home Alabama. Free Bird. Simple Man. Southern rock royalty brings the classics to the outdoor amphitheater on a summer night.',                                                         'https://rosemusiccenter.com',                 160),
('air-show-2026',        'Dayton Air Show — U.S. Navy Blue Angels',   'Jun 13–14, 2026',           'JUN','13', 'Dayton International Airport',             'family',  false, '$30–$60',               'The 2026 headliner is the U.S. Navy Blue Angels. One of the nation''s top air shows with WWII aircraft, aerobatics, and military flight demos.',                                            'https://www.daytonairshow.com',               170),
('pride-2026',           'Dayton Pride Festival',                      'Jun 5–6, 2026',             'JUN','5',  'Downtown Dayton',                         'festival', true,  null,                   'Dayton''s annual Pride celebration with a parade, live entertainment, food, and vendors in the heart of downtown. A beloved community tradition.',                                         'https://daytonpride.com',                     180),
('st-helen-fest',        'St. Helen Spring Festival',                  'Jun 5–7, 2026',             'JUN','5',  'St. Helen Parish, Dayton',                'family',  false, 'Free entry · rides & food sold', 'A classic Dayton parish festival with carnival rides, fair food, bingo, kids'' games, flea market, and a beer garden. A neighborhood summer staple.',                                    'https://www.sthelenfestival.org',             190),
('ys-street-fair-summer','Yellow Springs Street Fair',                 'Jun 14, 2026',              'JUN','14', 'Xenia Ave, Yellow Springs',               'arts',     true,  null,                   'Hundreds of artisan vendors, food, and live music in Dave Chappelle''s quirky, eclectic hometown — 25 minutes from Dayton and one of the best day trips around.',                          'https://www.yellowspringsohio.org/street-fair',200),
('fraze-summer',         'Fraze Pavilion Concert Series',              'Jun – Aug 2026',            'JUN','5',  'Fraze Pavilion, Kettering',               'music',   false, '$20–$75',               'Beautiful outdoor amphitheater in Kettering with national touring headliners all summer. Lawn tickets are great value — bring blankets and chairs.',                                         'https://fraze.com',                           210),
('kettering-sundays',    'Music Under the Stars — Kettering',          'Jun – Aug 2026 (Sunday evenings)', 'JUN','7', 'Fraze Pavilion Lawn, Kettering',    'music',    true,  null,                   'Free Sunday evening concerts on the Fraze Pavilion lawn all summer long. Bring a blanket, grab food from the trucks, and enjoy the evening.',                                               'https://www.ketteringoh.org/parks',           220),

-- July
('moulin-rouge-2026',    'Moulin Rouge! The Musical (Broadway)',       'Jul 22–26, 2026',           'JUL','22', 'Schuster Center, Downtown Dayton',        'arts',    false, '$50–$150',              'The dazzling Broadway hit comes to Dayton for a 5-night run. Spectacular costumes, iconic songs remixed, and a breathtaking love story.',                                                    'https://www.daytonlive.org',                  230),
('pop2000-fraze',        'Pop 2000 Tour — *NSYNC, O-Town, BBMak & More', 'Jul 10, 2026',           'JUL','10', 'Fraze Pavilion, Kettering',               'music',   false, '$30–$55',               'Chris Kirkpatrick of *NSYNC, O-Town, BBMak, Ryan Cabrera, and LFO bring the best of early 2000s pop to a warm Kettering summer night.',                                                      'https://fraze.com',                           240),
('parker-mccollum-nutter','Parker McCollum with Gabby Barrett & Kassi Ashton', 'Jul 25, 2026',     'JUL','25', 'Nutter Center, Fairborn',                 'music',   false, '$35–$75',               'Rising country star Parker McCollum headlines with Gabby Barrett and Kassi Ashton. A great outdoor country night just minutes from WPAFB.',                                                  'https://www.nuttercenter.com',                250),
('americana-fest',       'Centerville Americana Festival',             'Jul 4, 2026',               'JUL','4',  'Downtown Centerville',                    'family',   true,  null,                   'Ohio''s largest single-day Fourth of July celebration — 85,000 attendees, 5K run, parade, classic car show, street fair, and live entertainment all day long.',                            'https://www.centervilleamericana.org',         260),
('montgomery-fair',      'Montgomery County Fair',                     'Jul 12–18, 2026',           'JUL','12', 'Montgomery County Fairgrounds, Dayton',    'family',  false, '$5–$10',                'Full week county fair with carnival rides, 4H exhibits, livestock shows, demolition derby, grandstand concerts, and all the fried fair food you can eat.',                                  'https://www.montcofair.com',                  270),
('miamisburg-mound',     'Miamisburg Mound Festival',                  'Jul 10–12, 2026',           'JUL','10', 'Mound Park, Miamisburg',                  'festival', true,  null,                   'Annual celebration at one of the largest Adena mounds in Ohio — carnival rides, live music, food vendors, and fireworks. Free to attend.',                                                  'https://www.miamisburg.org',                  280),
('celtic-fest',          'Dayton Celtic Festival',                     'Jul 24–26, 2026',           'JUL','24', 'Riverscape, Downtown Dayton',             'festival', true,  null,                   'Three days of Irish and Scottish culture on the riverfront — live Celtic music, highland games, traditional food, whiskey tastings, and clan tents.',                                       'https://daytonceltfest.com',                  290),
('brewfest-2026',        'Dayton Craft Beer Fest',                     'Jul 18, 2026',              'JUL','18', 'Fifth Street Brewpub District',            'food',    false, '$35–$55',               'Sample 100+ craft beers from 30+ local breweries. Dayton has more craft breweries per capita than almost anywhere in the Midwest.',                                                          'https://www.visitdayton.com',                 300),

-- August
('for-king-country-fraze','for KING + COUNTRY — World On Fire Tour',  'Aug 5, 2026',               'AUG','5',  'Fraze Pavilion, Kettering',               'music',   false, '$30–$65',               'Australian Christian pop duo brings their massive World On Fire production to Fraze Pavilion — known for one of the most spectacular live shows in music today.',                            'https://fraze.com',                           310),
('goo-goo-dolls-rose',   'Goo Goo Dolls with Neon Trees',             'Aug 12, 2026',              'AUG','12', 'Rose Music Center, Huber Heights',         'music',   false, '$35–$75',               'Iris. Slide. Broadway. The Goo Goo Dolls bring their biggest hits to the outdoor amphitheater with Neon Trees opening. A perfect summer night.',                                            'https://rosemusiccenter.com',                 320),
('get-led-out-fraze',    'Get The Led Out — Led Zeppelin Tribute',    'Aug 12, 2026',              'AUG','12', 'Fraze Pavilion, Kettering',               'music',   false, '$25–$50',               'The most celebrated Led Zeppelin tribute in the country brings a full-production show including Kashmir, Whole Lotta Love, and Stairway to Heaven.',                                         'https://fraze.com',                           330),
('arena-rock-fraze',     'That Arena Rock Show — 70s & 80s Rock',     'Aug 21, 2026',              'AUG','21', 'Fraze Pavilion, Kettering',               'music',   false, '$20–$45',               'A massive celebration of the greatest era of rock — Journey, Foreigner, REO Speedwagon, and more performed live. Pure nostalgia under the summer sky.',                                      'https://fraze.com',                           340),
('greene-fair',          'Greene County Fair',                         'Aug 2–8, 2026',             'AUG','2',  'Greene County Fairgrounds, Xenia',         'family',  false, '$5–$10',                'Full week county fair with rides, 4H, demolition derby, grandstand acts, livestock judging, and all the classic fair food you can dream of.',                                               'https://www.greenecountyfair.org',            350),
('porchfest-2026',       'Dayton Porchfest',                           'Aug 22, 2026',              'AUG','22', 'Oregon District porches, Dayton',          'music',    true,  null,                   'Dozens of local bands play simultaneously on front porches across the Oregon District. A beloved Dayton original — wander the neighborhood all afternoon.',                                 'https://daytonporchfest.com',                 360),

-- September
('beavercreek-popcorn',  'Beavercreek Popcorn Festival',              'Sep 11–13, 2026',           'SEP','11', 'Downtown Beavercreek',                    'festival', true,  null,                   'One of the region''s most unique fall festivals — live entertainment, arts & crafts, food vendors, and endless varieties of popcorn. Free and family-friendly.',                            'https://www.beavercreekpopcornfestival.com',  370),
('oktoberfest-dai',      'Dayton Art Institute Oktoberfest',           'Sep 25–27, 2026',           'SEP','25', 'Dayton Art Institute',                    'food',    false, 'Free entry · food & beer sold', 'One of Ohio''s premier Oktoberfest events — authentic German food, imported beers on the museum''s stunning terrace, live oompah music, and stein-holding contests.',              'https://www.daytonartinstitute.org/oktoberfest',380),

-- October
('the-notebook-schuster','The Notebook — Broadway Musical',            'Oct 6–11, 2026',            'OCT','6',  'Schuster Center, Downtown Dayton',        'arts',    false, '$45–$130',              'The beloved love story comes to life on the Schuster stage for a 6-night Broadway run. Beautiful music, stunning staging, and a story that will leave you in tears.',                       'https://www.daytonlive.org',                  390),
('outdoor-experience',   'Wagner Subaru Outdoor Experience',           'Oct 3–4, 2026',             'OCT','3',  'Eastwood MetroPark, Dayton',              'family',   true,  null,                   'Free outdoor adventure festival at Eastwood MetroPark — kayaking demos, archery, rock climbing, nature hikes, live entertainment, and activities for all ages.',                            'https://www.metroparks.org',                  400),
('springboro-pumpkin',   'Springboro Pumpkin Show',                    'Oct 8–11, 2026',            'OCT','8',  'Historic Downtown Springboro',            'family',   true,  null,                   'One of the region''s favorite fall festivals — pumpkins, hayrides, carnival rides, live music, and fall food in a charming downtown setting.',                                              'https://springboropumpkinshow.com',           410),
('ys-street-fair-fall',  'Yellow Springs Street Fair (Fall)',          'Oct 11, 2026',              'OCT','11', 'Xenia Ave, Yellow Springs',               'arts',     true,  null,                   'The fall edition of Yellow Springs'' beloved bi-annual street fair — artisan vendors, food, and live music with the colors of autumn as the perfect backdrop.',                             'https://www.yellowspringsohio.org/street-fair',420),
('tipp-apple-butter',    'Tipp City Apple Butter Festival',            'Oct 17–18, 2026',           'OCT','17', 'Historic Downtown Tipp City',             'festival', true,  null,                   'Beloved harvest festival in charming Tipp City — apple butter making demos, arts & crafts, live music, and fall treats on historic Main Street.',                                           'https://tippcityapplebutterestival.com',      430),
('zombie-walk',          'Oregon District Halloween Night',            'Oct 24, 2026',              'OCT','24', 'Oregon District, Dayton',                 'festival', true,  null,                   'Thousands gather in the Oregon District for Dayton''s wildly popular Halloween street event. Epic costumes, great bars, live music, and organized chaos.',                                  'https://theoregondistrict.org',               440),

-- November / December
('woodland-lights',      'Woodland Lights',                            'Nov 20 – Dec 30, 2026',     'NOV','20', 'Carriage Hill MetroPark, Huber Heights',   'family',  false, '$10–$20 per car',       'Drive through millions of lights at Carriage Hill MetroPark. One of the Miami Valley''s most magical holiday traditions — perfect for the whole family.',                                   'https://www.metroparks.org',                  450),
('holiday-festival',     'Dayton Holiday Festival',                    'Nov 27 – Dec 31, 2026',     'NOV','27', 'Courthouse Square & Downtown Dayton',     'family',   true,  null,                   'Month-long downtown celebration with nightly light shows, ice skating, live music, tree lighting ceremony, and holiday markets every weekend.',                                              'https://www.downtowndayton.org/holiday-festival',460),

-- Year-Round
('art-after-dark',       'Dayton Art Institute: Art After Dark',       'Monthly (2nd Fri of each month)', 'MON','2nd', 'Dayton Art Institute',             'arts',    false, '$10–$15',               'Monthly themed evening events at DAI — cocktails, live music, and full gallery access. Themes change every month. One of Dayton''s best date nights.',                                      'https://www.daytonartinstitute.org',          470)

on conflict (id) do nothing;
